on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: equipe200.tch099.ovh 
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        port: 22
        source: "./site/*.php,./site/*.html"
        target: "./"
        strip_components: 1

